[package]
name = "svix-bridge-plugin-queue"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
svix-bridge-types.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-executor-trait = "2.1"
tokio-reactor-trait = "1.1"
tracing = "0.1"

[dependencies.omniqueue]
git = "https://github.com/svix/omniqueue-rs"
rev = "62ca8fa5cb0ac47bbfbad4b1939bcfe7d4cdfb6b"
default-features = false
features = ["gcp_pubsub", "rabbitmq", "redis", "sqs"]

[dev-dependencies]
aws-config = "1.1.5"
aws-sdk-sqs = "1.13.0"
fastrand = "2.0.1"
google-cloud-googleapis = "0.12.0"
google-cloud-pubsub = "0.24.0"
lapin = "2"
redis = { version = "0.25.4", features = ["tokio-comp", "streams"] }
tracing-subscriber.workspace = true
wiremock.workspace = true
