[package]
name = "svix-bridge-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
serde_json.workspace = true
svix = "1.17.0"
