[package]
name = "svix-bridge-types"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
svix = { version = "1.24.0", features = ["svix_beta"] }
