name: Javascript Lint
on:
  pull_request:
    paths:
      - "javascript/**"
      - "openapi.json"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh

      - name: Install modules
        run: |
          cd javascript
          yarn

      - name: Lint
        run: |
          cd javascript
          yarn run lint
