name: Rust Lint

on:
  push:
    branches:
      - main
    paths:
      - 'rust/**'
      - '.github/workflows/rust-lint.yml'
  pull_request:
    paths:
      - 'rust/**'
      - '.github/workflows/rust-lint.yml'
      - "openapi.json"

jobs:
  test-versions:
    name: Rust Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
    - uses: actions/checkout@master

    - name: Regen openapi libs
      run: |
        yarn
        ./regen_openapi.sh

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust

    - name: Clippy
      run: cargo clippy --manifest-path rust/Cargo.toml --all --all-targets --all-features -- -D warnings

    - name: rustfmt
      run: cargo fmt --manifest-path rust/Cargo.toml --all -- --check

    - name: Run tests
      run: cargo test --manifest-path rust/Cargo.toml --all
